name: Run Robot Framework Web Tests on Windows

on:
  push:
    branches:
      - master  # Atau branch lain yang diinginkan
  pull_request:
    branches:
      - master  # Atau branch lain yang diinginkan
  schedule:
    # Menjalankan workflow setiap jam pada menit ke-0
    - cron: '0 * * * *'  # Cron expression untuk setiap jam

jobs:
  test:
    runs-on: windows-latest  # Menjalankan job di Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'  # Tentukan versi Python yang diinginkan

      # Langkah 3: Install dependencies
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Menginstal dependensi dari file requirements.txt

      # Langkah 4: Install WebDriver (ChromeDriver di Windows)
      # - name: Install ChromeDriver
      #   run: |
      #     Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_win32.zip -OutFile chromedriver.zip
      #     Expand-Archive -Path chromedriver.zip -DestinationPath C:\chromedriver
      #     $env:Path += ";C:\chromedriver"

      # Langkah 5: Jalankan Robot Framework Tests
      - name: Run Robot Framework Tests
        run: |
          # robot -d report/ -v env:web_eProc -i test '.\testSuite\Tim OP\*.robot'
          robot -d report/ -v env:web_eProc -i test '.\testSuite\Tim OP\test_createProject.robot'
