name: Run Robot Framework Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12.5

      # Langkah 3: Install dependencies
      - name: Install dependencies from requirements.txt
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Langkah 4: Debugging - Print working directory dan list files di testSuite
      - name: Print working directory and list files in testSuite
        run: |
          echo "Current directory:"
          pwd  # Menampilkan direktori kerja
          echo "Listing contents of eProc-Web/testSuite/Tim_OP"
          ls -l /home/runner/work/eProc-Web/eProc-Web/testSuite  # Menampilkan file di dalam testSuite/Tim OP

      # Langkah 5: Verifikasi apakah file ada
      - name: Check if test_createProject.robot exists
        run: |
          if [ -f "/home/runner/work/eProc-Web/eProc-Web/testSuite/Tim_OP/test_createProject.robot" ]; then
            echo "File exists!"
          else
            echo "File does not exist!"
          fi

      # Langkah 6: Run Robot Framework Tests
      - name: Run Robot Framework Tests
        run: |
          source .venv/bin/activate
          robot /home/runner/work/eProc-Web/eProc-Web/testSuite/Tim_OP/test_createProject.robot
