name: Run Robot Framework Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: '0 * * * *'  # Menjadwalkan setiap jam pada menit ke-0

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.5

      # Step 3: Install dependencies
      - name: Install dependencies from requirements.txt
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Change to correct directory
      - name: Change to test directory
        run: cd eProc-Web/testSuite

      # Step 5: Run Robot Framework Tests with correct path
      - name: Run Robot Framework Tests
        run: |
          source .venv/bin/activate
          python -m robot.run --resource ${GITHUB_WORKSPACE}/eProc-Web/testSuite/pageObject/generalFunct.robot --suite eProc-Web.testSuite.Tim\ OP.test_createProject --outputdir $GITHUB_WORKSPACE/results .

      # Step 6: Upload Test Report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: rf-results
          path: results/


# project-root/

# ├── eProc-Web/
# │   ├── pageObject/
# │   │   ├── detailProject/
# │   │   │   ├── Tim OP/
# │   │   │   │   ├── pom_createProject.robot
# │   │       ├── generalFunct.robot
# │   │       └── API_listKecamatan.robot
# │   │
# │   ├── testScenario/
# │   │   ├── Tim OP
# │   │   │   ├── createProject.robot
# │   │
# │   ├── testSuite/
# │   │   ├── Tim OP
# │   │   │   ├── test_createProject.robot
