name: Robot Test - Test Create Project (Administrator)
on:
  schedule:
    - cron: '30 5 * * 1,3'  # Senin dan Rabu pukul 5:30 AM UTC
    - cron: '30 5 * * 2,4'  # Selasa dan Kamis pukul 5:30 AM UTC

  push:
    branches: [ master ]
    paths:
      - "testSuite/Tim_OP/test_createProject.robot"

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework Test
        run: |
          robot --outputdir results testSuite/Tim_OP/test_createProject.robot | tee robot_output.log

      - name: Extract Test Summaries
        id: extract
        run: |
          summary=$(sed -n '2p' robot_output.log | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          details=$(grep -E '[0-9]+ tests, [0-9]+ passed, [0-9]+ failed' robot_output.log | tail -n1)
          echo "summary=$summary" >> $GITHUB_OUTPUT
          echo "details=$details" >> $GITHUB_OUTPUT
          echo "Extracted summary: $summary"
          echo "Extracted details: $details"

      - name: Upload Robot Framework Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: results/

      - name: Send Slack Notification (text only)
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "*[Robot Test - '"${{ steps.extract.outputs.summary }}"']*\nResult: '"${{ steps.extract.outputs.details }}"'\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Lihat detail di GitHub Actions>"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
